### ISSUE TITLE
Allow adding Colorpleth map as a layer to an existing map

### ISSUE THREAD

**Issue by omrihar** [voluntadpear/vue-choropleth#1]
Hi,

I just discovered this library and I think it's really nice and elegant! My problem is that I already have
a `Vue2Leaflet` map and only want to add a Colorpleth map as a GeoJSON layer.
I guess it should not be too complicated to implement this as a layer + controls rather than a complete solution? I think this can be very useful!

Thanks!
Omri

**Comment by voluntadpear** [comment]
Hi,

you're definitely right! I think moving the `v-geojson-layer` from the `ChoroplethMap` component to a new one (like `ChoroplethLayer` or something) would be a possible approach, and changing the API so you include it inside the scoped slot (like `InfoControl` and `ReferenceChart`). 

This way, for your use case you could use this new `ChoroplethLayer` component into your map, without the whole `ChoroplethMap` component.

I'll look into this with a little time. If you end doing the separation yourself for your use case, feel free to send a PR :)

Thanks!

**Comment by voluntadpear** [comment]
I finally managed to get a little time to work on this and the API for the new version `0.1.0` has changed completely to be used inside a `v-map`. You can check the updated examples to see how it works now. 🎉

Thanks once again for your suggestion! 😀

**Comment by omrihar** [comment]
Awesome!

In the meantime I already implemented my own solution inspired by your work. I just added a geojson layer with a style function whose color depends on some property from the geojson object. For my next project I'll use your more complete solution instead :)

Thanks,
Omri
