### ISSUE TITLE
Error in beforeDestroy hook with 'removeLayer'

### ISSUE THREAD

**Issue by justice47** [voluntadpear/vue-choropleth#11]
When the component is destroyed:
**[Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'removeLayer' of undefined"**

**Comment by justice47** [comment]
This is the problem with old version of [vue2-leaflet](https://github.com/KoRiGaN/Vue2Leaflet), included in the package.
I've updated vue2-leaflet to the latest v2.1.1, problem disappears and all works like a charm.
Should I submit a commit with update to package.json?

**Comment by justice47** [comment]
Submitted PR #12

**Comment by voluntadpear** [comment]
Thanks. I released version `0.3.1` with your PR!
