### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by baoshenyi** [voluntadpear/vue-choropleth#2]
Good day,

I am new to vuejs and nodejs.

I download the source code from github and tried to build and got following error, could you please help me with it? 

I like to use it in my new project, earlier is better.

Thanks,

Shenyi

D:\Source\vuechoropleth>node -v
v8.9.1

D:\Source\vuechoropleth>npm -v
4.6.1

D:\Source\vuechoropleth>npm install
D:\Source\vuechoropleth>npm run build

> vue-choropleth@0.0.4 build D:\Source\vuechoropleth
> cd scripts && ./build.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-choropleth@0.0.4 build: `cd scripts && ./build.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-choropleth@0.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jerry Bao\AppData\Roaming\npm-cache\_logs\2018-01-08T04_52_59_617Z-debug.log

**Comment by voluntadpear** [comment]
Hi! 

I updated the project to get rid of the `build.sh` file, I suggest you to pull the latest changes and trying to run `npm run build` once again
