### ISSUE TITLE
Layer not render correctly (or what is expected) when the min value is 0.

### ISSUE THREAD

**Issue by skarampatakis** [voluntadpear/vue-choropleth#3]
Hi, 
thank you for your very helpful plugin. I have managed to install it correctly and made some tests. 

However I am having a problem when the min value on the dataset is 0. 

If the only values on the dataset is 0 and 100, then I get this layer.

![image](https://user-images.githubusercontent.com/2419820/35933650-e4407bbc-0c43-11e8-81cb-6c676bd97c81.png)

If I manually edit the data and insert a let say "dummy" item with value even 0.1 then the polygons with value 100 and the dummy get colored but those with 0 get no color again.

![image](https://user-images.githubusercontent.com/2419820/35933738-27a537bc-0c44-11e8-88d4-d581a0406c60.png)

If there are other values between 0 and 100, then I get this layer

![image](https://user-images.githubusercontent.com/2419820/35933533-8e752ef8-0c43-11e8-895c-946c812c2f7a.png)

It seems that somehow the polygons with 0 value are ignored and have no color at all. 

Am I missing something? Do you have any suggestion? I believe that there must be something with the utils function but not sure. Thank you for your time.

**Comment by voluntadpear** [comment]
Hi! this is definitely a bug with the component, it should work with values of 0.

I'll look into this

Thank you!

**Comment by voluntadpear** [comment]
I've just released version 0.1.1 with fixes for your problem!

Hopefully it'll be solved now :)

**Comment by skarampatakis** [comment]
That was quick! Thank you! It works great!
