### ISSUE TITLE
Get data from API call

### ISSUE THREAD

**Issue by skarampatakis** [voluntadpear/vue-choropleth#4]
So far I am able to load data from a static file and successfully render the map. However I would like to be able to load data from an API and finally update them on an event. 

I have tried this but nothing happens.

```javascript
export default {
  name: "app",
  components: { 
    'v-map': Vue2Leaflet.Map,
    'v-info-control': VueChoropleth.InfoControl, 
    'v-reference-chart': VueChoropleth.ReferenceChart, 
    'v-choropleth-layer': VueChoropleth.ChoroplethLayer 
  },
  data() {
    return {
      indexData: [],
      kallikratis,
      show: true,
      colorScale: ["F90606", "0616F9", "#00FF00"],
      value: {
        key: "value",
        metric: "%"
      },
      
      mapOptions: {
        attributionControl: false
      },
    }
  },
  created(){
    axios.get("/api/mapValues?index=1").then(response => {
    console.log(response.data);
    this.indexData = response.data;    
}
);
},
}
```
Instead I get only the polygons without any color.

**Comment by skarampatakis** [comment]
It seems that the data get loaded, but the color function is not run again, so the layer does not get updated. However when I hover over a polugon I get the correct data. Is there somehow a function to trigger in order to update the map? 

I do not have much experience with Vue so it is difficult to debug it myself. From what I have figured out is that somehow have to update the geojsonOptions object, since this holds the fill property. Any hint? 

Thank you for your help in advance.

**Comment by voluntadpear** [comment]
It should update automatically thanks to the reactivity system of Vue. Unfortunately, maybe some DOM manipulation steps that are currently running on the `mounted` hook need to be fixed to react to changes.

I'll look into this with a bit of time

**Comment by skarampatakis** [comment]
That was my thought also but seems not to happen. Please inform if you need any more info about this from me. You can reproduce the error on your node example.

**Comment by voluntadpear** [comment]
I didn't still decide what would be the best approach to fix it, but as a workaround you can use `<v-choropleth-layer v-if="indexData.length" ... />` to mount the component only when you have the data ready

**Comment by voluntadpear** [comment]
I just release version 0.1.2 with a fix for this problem. It should be working now.

Thanks for bringing this issue up and please let me know if it's now working.

As a little side-note: Even with this fix the conditional render approach I suggested previously is not just a workaround, you can use it to handle how you'll let the user know that there's a data fetching in progress (via spinners, etc.) and load the map only when the data has arrived.

**Comment by skarampatakis** [comment]
Thank you for your support. It works!
