### ISSUE TITLE
Minor Issue in node-example/src/App.vue and README

### ISSUE THREAD

**Issue by blabadie1** [voluntadpear/vue-choropleth#6]
Hi, 

In the "How to use" section of the README and App.vue of the Node example, the Vue2Leaflet Map component is imported like this (shown below in the picture): 
'v-map' : Vue2Leaflet.Map,

However, when I tried using this component (I just used the component file and separately installed all the packages), I kept getting an error about v-map being unregistered. After looking at the Vue2Leaflect documentation, I found that if I changed the line to 'v-map' : Vue2Leaflet.LMap, then the component worked. Not sure if this is due to updated packages or something else I was missing, but thought I would leave this here just in case.
![vue-choropleth](https://user-images.githubusercontent.com/34427979/43734415-a5021da0-9985-11e8-8120-1730b045fb54.PNG)

**Comment by voluntadpear** [comment]
Hi @blabadie1, you're right. `Vue2Leaflet` changed all of its components' names on release `v1.0.0`.

I just released `v0.2.0` of `vue-choropleth` that updates the README and also the names of our components to maintain consistency with `Vue2Leaflet`.

Thank you for bringing this up!
