### ISSUE TITLE
Problem with

### ISSUE THREAD

**Issue by plicplic** [voluntadpear/vue-choropleth#7]
I have an issue with the new props and got this warning:

**[Vue warn]: Invalid prop: type check failed for prop "strokeColor". Expected String, got Number.**
And same warning for currentStrokeColor too.

If I use a number (like 666 or 999) I got this message. It doesn't work with six-characters values.

Wondering if I use it wrong ?

Thanks

**Comment by voluntadpear** [comment]
@plicplic Yes, you need to provide the prop as a string, it seems you're doing `:strokeColor="666"` and you would need to do either `:strokeColor="'666'"` or `strokeColor="666"` (without the `v-bind` directive) in order for it to work. Let me know if it works for you.

**Comment by plicplic** [comment]
@voluntadpear Oh yes, I failed to provide a string, indeed. Now that works like a charm. Thanks for your prompt response!
